'use strict';

// 目标语言表：每个语言码都用免费 Google 端点实测过能真实翻译（199/205 通过，
// 未通过的已剔除）。中英文名取自 Intl.DisplayNames（CLDR），少数 Google 专有
// 码手工补名。COMMON 在 popup 里露出，全表在设置页。
// 生成脚本见 docs/openimmersive-语言表生成-0729.md
(function (root, factory) {
  if (typeof module !== 'undefined' && module.exports) module.exports = factory();
  else root.YLLangs = factory();
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  const ALL = [
  ['ab', "Abkhazian", "阿布哈西亚语"],
  ['ace', "Acehnese", "亚齐语"],
  ['ach', "Acoli", "阿乔利语"],
  ['aa', "Afar", "阿法尔语"],
  ['af', "Afrikaans", "南非荷兰语"],
  ['ak', "Akan", "阿肯语"],
  ['sq', "Albanian", "阿尔巴尼亚语"],
  ['alz', "Alur", "阿卢尔语"],
  ['am', "Amharic", "阿姆哈拉语"],
  ['ar', "Arabic", "阿拉伯语"],
  ['hy', "Armenian", "亚美尼亚语"],
  ['as', "Assamese", "阿萨姆语"],
  ['awa', "Awadhi", "阿瓦德语"],
  ['ay', "Aymara", "艾马拉语"],
  ['az', "Azerbaijani", "阿塞拜疆语"],
  ['ban', "Balinese", "巴厘语"],
  ['bal', "Baluchi", "俾路支语"],
  ['bm', "Bambara", "班巴拉语"],
  ['bn', "Bangla", "孟加拉语"],
  ['eu', "Basque", "巴斯克语"],
  ['be', "Belarusian", "白俄罗斯语"],
  ['bem', "Bemba", "本巴语"],
  ['bew', "Betawi", "Betawi"],
  ['bho', "Bhojpuri", "博杰普尔语"],
  ['bik', "Bikol", "比科尔语"],
  ['bs', "Bosnian", "波斯尼亚语"],
  ['br', "Breton", "布列塔尼语"],
  ['bg', "Bulgarian", "保加利亚语"],
  ['bua', "Buriat", "布里亚特语"],
  ['my', "Burmese", "缅甸语"],
  ['yue', "Cantonese", "粤语"],
  ['ca', "Catalan", "加泰罗尼亚语"],
  ['ceb', "Cebuano", "宿务语"],
  ['cv', "Chuvash", "楚瓦什语"],
  ['co', "Corsican", "科西嘉语"],
  ['hr', "Croatian", "克罗地亚语"],
  ['cs', "Czech", "捷克语"],
  ['da', "Danish", "丹麦语"],
  ['dv', "Divehi", "迪维希语"],
  ['doi', "Dogri", "多格拉语"],
  ['nl', "Dutch", "荷兰语"],
  ['dyu', "Dyula", "迪尤拉语"],
  ['dz', "Dzongkha", "宗卡语"],
  ['en', "English", "英语"],
  ['eo', "Esperanto", "世界语"],
  ['et', "Estonian", "爱沙尼亚语"],
  ['ee', "Ewe", "埃维语"],
  ['fo', "Faroese", "法罗语"],
  ['fj', "Fijian", "斐济语"],
  ['fil', "Filipino", "菲律宾语"],
  ['fi', "Finnish", "芬兰语"],
  ['fon', "Fon", "丰语"],
  ['fr', "French", "法语"],
  ['fur', "Friulian", "弗留利语"],
  ['gaa', "Ga", "加族语"],
  ['gl', "Galician", "加利西亚语"],
  ['lg', "Ganda", "卢干达语"],
  ['ka', "Georgian", "格鲁吉亚语"],
  ['de', "German", "德语"],
  ['el', "Greek", "希腊语"],
  ['gn', "Guarani", "瓜拉尼语"],
  ['gu', "Gujarati", "古吉拉特语"],
  ['ht', "Haitian Creole", "海地克里奥尔语"],
  ['cnh', "Hakha Chin", "哈卡钦语"],
  ['ha', "Hausa", "豪萨语"],
  ['haw', "Hawaiian", "夏威夷语"],
  ['iw', "Hebrew", "希伯来语"],
  ['hi', "Hindi", "印地语"],
  ['hmn', "Hmong", "苗语"],
  ['hu', "Hungarian", "匈牙利语"],
  ['iba', "Iban", "伊班语"],
  ['is', "Icelandic", "冰岛语"],
  ['ig', "Igbo", "伊博语"],
  ['ilo', "Iloko", "伊洛卡诺语"],
  ['id', "Indonesian", "印度尼西亚语"],
  ['iu', "Inuktitut", "因纽特语"],
  ['ga', "Irish", "爱尔兰语"],
  ['it', "Italian", "意大利语"],
  ['jam', "Jamaican Creole English", "Jamaican Creole English"],
  ['ja', "Japanese", "日语"],
  ['jw', "Javanese", "爪哇语"],
  ['kac', "Kachin", "克钦语"],
  ['kl', "Kalaallisut", "格陵兰语"],
  ['kn', "Kannada", "卡纳达语"],
  ['kau', "Kanuri", "卡努里语"],
  ['kk', "Kazakh", "哈萨克语"],
  ['kha', "Khasi", "卡西语"],
  ['km', "Khmer", "高棉语"],
  ['rw', "Kinyarwanda", "卢旺达语"],
  ['ktu', "Kituba", "基图巴语"],
  ['trp', "Kokborok", "科克博罗克语"],
  ['kg', "Kongo", "刚果语"],
  ['gom', "Konkani", "孔卡尼语"],
  ['ko', "Korean", "韩语"],
  ['kri', "Krio", "Krio"],
  ['ku', "Kurdish", "库尔德语"],
  ['ckb', "Kurdish (Sorani)", "库尔德语（索拉尼）"],
  ['ky', "Kyrgyz", "柯尔克孜语"],
  ['lo', "Lao", "老挝语"],
  ['la', "Latin", "拉丁语"],
  ['lv', "Latvian", "拉脱维亚语"],
  ['lij', "Ligurian", "利古里亚语"],
  ['li', "Limburgish", "林堡语"],
  ['ln', "Lingala", "林加拉语"],
  ['lt', "Lithuanian", "立陶宛语"],
  ['lmo', "Lombard", "伦巴第语"],
  ['luo', "Luo", "卢奥语"],
  ['lb', "Luxembourgish", "卢森堡语"],
  ['mk', "Macedonian", "马其顿语"],
  ['mad', "Madurese", "马都拉语"],
  ['mai', "Maithili", "迈蒂利语"],
  ['mak', "Makasar", "望加锡语"],
  ['mg', "Malagasy", "马拉加斯语"],
  ['ms', "Malay", "马来语"],
  ['ms-Arab', "Malay (Jawi)", "马来语（爪夷文）"],
  ['ml', "Malayalam", "马拉雅拉姆语"],
  ['mt', "Maltese", "马耳他语"],
  ['mam', "Mam", "马姆语"],
  ['mi', "Māori", "毛利语"],
  ['mr', "Marathi", "马拉地语"],
  ['mni-Mtei', "Meiteilon (Manipuri)", "曼尼普尔语"],
  ['min', "Minangkabau", "米南佳保语"],
  ['lus', "Mizo", "米佐语"],
  ['mn', "Mongolian", "蒙古语"],
  ['mfe', "Morisyen", "毛里求斯克里奥尔语"],
  ['ne', "Nepali", "尼泊尔语"],
  ['no', "Norwegian", "挪威语"],
  ['nus', "Nuer", "努埃尔语"],
  ['ny', "Nyanja", "齐切瓦语"],
  ['or', "Odia", "奥里亚语"],
  ['om', "Oromo", "奥罗莫语"],
  ['pam', "Pampanga", "邦板牙语"],
  ['pag', "Pangasinan", "邦阿西南语"],
  ['pap', "Papiamento", "帕皮阿门托语"],
  ['ps', "Pashto", "普什图语"],
  ['fa', "Persian", "波斯语"],
  ['pl', "Polish", "波兰语"],
  ['pt', "Portuguese", "葡萄牙语"],
  ['pa', "Punjabi", "旁遮普语"],
  ['qu', "Quechua", "克丘亚语"],
  ['ro', "Romanian", "罗马尼亚语"],
  ['rom', "Romany", "吉普赛语"],
  ['rn', "Rundi", "隆迪语"],
  ['ru', "Russian", "俄语"],
  ['sm', "Samoan", "萨摩亚语"],
  ['sa', "Sanskrit", "梵语"],
  ['sat', "Santali", "桑塔利语"],
  ['gd', "Scottish Gaelic", "苏格兰盖尔语"],
  ['nso', "Sepedi", "北索托语"],
  ['sr', "Serbian", "塞尔维亚语"],
  ['shn', "Shan", "掸语"],
  ['sn', "Shona", "绍纳语"],
  ['scn', "Sicilian", "西西里语"],
  ['szl', "Silesian", "西里西亚语"],
  ['zh-CN', "Simplified Chinese", "简体中文"],
  ['sd', "Sindhi", "信德语"],
  ['si', "Sinhala", "僧伽罗语"],
  ['sk', "Slovak", "斯洛伐克语"],
  ['sl', "Slovenian", "斯洛文尼亚语"],
  ['so', "Somali", "索马里语"],
  ['st', "Southern Sotho", "南索托语"],
  ['es', "Spanish", "西班牙语"],
  ['su', "Sundanese", "巽他语"],
  ['sus', "Susu", "苏苏语"],
  ['sw', "Swahili", "斯瓦希里语"],
  ['sv', "Swedish", "瑞典语"],
  ['tl', "Tagalog", "他加禄语"],
  ['tg', "Tajik", "塔吉克语"],
  ['ta', "Tamil", "泰米尔语"],
  ['tt', "Tatar", "鞑靼语"],
  ['te', "Telugu", "泰卢固语"],
  ['tet', "Tetum", "德顿语"],
  ['th', "Thai", "泰语"],
  ['ti', "Tigrinya", "提格利尼亚语"],
  ['tiv', "Tiv", "蒂夫语"],
  ['tpi', "Tok Pisin", "托克皮辛语"],
  ['zh-TW', "Traditional Chinese", "繁体中文"],
  ['ts', "Tsonga", "聪加语"],
  ['tum', "Tumbuka", "通布卡语"],
  ['tr', "Turkish", "土耳其语"],
  ['tk', "Turkmen", "土库曼语"],
  ['udm', "Udmurt", "乌德穆尔特语"],
  ['uk', "Ukrainian", "乌克兰语"],
  ['ur', "Urdu", "乌尔都语"],
  ['ug', "Uyghur", "维吾尔语"],
  ['uz', "Uzbek", "乌兹别克语"],
  ['ve', "Venda", "文达语"],
  ['vec', "Venetian", "威尼斯语"],
  ['vi', "Vietnamese", "越南语"],
  ['war', "Waray", "瓦瑞语"],
  ['cy', "Welsh", "威尔士语"],
  ['fy', "Western Frisian", "西弗里西亚语"],
  ['wo', "Wolof", "沃洛夫语"],
  ['xh', "Xhosa", "科萨语"],
  ['yi', "Yiddish", "意第绪语"],
  ['yo', "Yoruba", "约鲁巴语"],
  ['yua', "Yucatec Maya", "尤卡坦玛雅语"],
  ['zap', "Zapotec", "萨波蒂克语"],
  ['zu', "Zulu", "祖鲁语"],
  ];
  const COMMON = ["zh-CN","zh-TW","en","ja","ko","fr","de","es","ru","pt","it","ar","hi","th","vi","id","tr","pl","nl","uk"];
  const NAME = {};
  for (const [code, en, zh] of ALL) NAME[code] = zh + '（' + en + '）';
  return { ALL, COMMON, NAME, count: ALL.length };
});
